#!/bin/bash
echo "=" >> "=" >> "=" >> "=" >> "="
echo "VOLUME 4 VERIFICATION REPORT"
echo "=" >> "=" >> "=" >> "=" >> "="
echo ""

echo "📊 File Statistics:"
echo "-------------------"
echo "modules.js total lines: $(wc -l < modules.js)"
echo "volume4-content.js lines: $(wc -l < volume4-content.js)"
echo ""

echo "📚 Chapter Count:"
echo "-------------------"
echo "Volume 4 Welcome: $(grep -c "vol4-welcome" modules.js)"
echo "Chapter 70 (Threat Detection): $(grep -c "vol4-ch70" modules.js)"
echo "Chapter 71 (Incident Response): $(grep -c "vol4-ch71" modules.js)"
echo "Chapter 72 (SIEM): $(grep -c "vol4-ch72" modules.js)"
echo "Chapter 73 (Vulnerability): $(grep -c "vol4-ch73" modules.js)"
echo "Chapter 74 (Compliance): $(grep -c "vol4-ch74" modules.js)"
echo "Chapter 75 (Threat Intel): $(grep -c "vol4-ch75" modules.js)"
echo "Chapter 76 (Phishing): $(grep -c "vol4-ch76" modules.js)"
echo "Chapter 77 (Insider Threat): $(grep -c "vol4-ch77" modules.js)"
echo "Chapter 78 (Forensics): $(grep -c "vol4-ch78" modules.js)"
echo "Chapter 79 (SOAR): $(grep -c "vol4-ch79" modules.js)"
echo "Chapter 80 (Zero Trust): $(grep -c "vol4-ch80" modules.js)"
echo "Chapter 81 (AI Security): $(grep -c "vol4-ch81" modules.js)"
echo ""

TOTAL_V4_CHAPTERS=$(grep -c "vol4-ch[0-9]" modules.js)
echo "✅ Total Volume 4 chapters: $TOTAL_V4_CHAPTERS"
echo ""

echo "🔍 Syntax Check:"
echo "-------------------"
node -c modules.js && echo "✅ JavaScript syntax valid" || echo "❌ Syntax errors found"
echo ""

echo "📦 Module Export:"
echo "-------------------"
grep -q "module.exports = courseModules" modules.js && echo "✅ Export statement found" || echo "❌ Export statement missing"
echo ""

echo "=" >> "=" >> "=" >> "=" >> "="
echo "VERIFICATION COMPLETE"
echo "=" >> "=" >> "=" >> "=" >> "="
